### ISSUE TITLE
"Use this template" button doesn't fully work yet

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/r.pkg.template#35]
It only make a new duplicate of the repo at the moment, and requires manual update of the files.  

I think following the README instruction is still the best strategy at the moment.

**Comment by dinakar29** [comment]
That's actually how Github templates work. You're probably expecting the same behavior as [`cookiecutter`](https://cookiecutter.readthedocs.io/en/2.0.2/), but alas, Github template repos do not work that way.

**Comment by shajoezhu** [comment]
Yes, kinda, i was hoping github at some stage would roll out some more advanced template creation, allow user to specify some parameter and enable user to customise  

I was wondering shall we make a bash script to automate this process, 

and use github action to automatic do a second commit after the "initial commit" 

Similar to statsspa or enabler creating new roche github repos. What do you think?

**Comment by dinakar29** [comment]
That's a good idea. We'll implement that as a feature on this repo, where the bash script asks for prompts from the user instead of them having to run those commands for initialization.

As for doing a Github Action to do the second commit - we should probably leave that to the user to decide how they want to populate the repository before we auto-commit something.
